version: '3.8'

services:
  api:
    image: api-n5-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Mapea el puerto 5000 del host al puerto 80 del contenedor
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=GRIMANIEL_HP\\MSSQLSERVER01;Database=N5Database;Integrated Security=True;TrustServerCertificate=True;
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app-network
    volumes:
      - esdata:/usr/share/elasticsearch/data

networks:
  app-network:
    driver: bridge

volumes:
  esdata: