version: '3.8'

services:
  api:
    image: api-n5-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Mapea el puerto 5000 del host al puerto 80 del contenedor
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=GRIMANIEL_HP\\MSSQLSERVER01;Database=N5Database;Integrated Security=True;TrustServerCertificate=True;
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
